PlusToolkit/PlusLib

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h, src/PlusVolumeReconstruction/vtkPlusVolumeReconstructor.cxx
Also fixes the bug introduced by the git merge of XML utility function renames.
=> Adding new configurable parameters for Capistrano

src/PlusVolumeReconstruction/CMakeLists.txt, src/PlusVolumeReconstruction/vtkPlusVolumeReconstructor.cxx
=> re #1148 linking to necessary ITK dependency

src/PlusCommon/PlusXmlUtils.h, src/PlusVolumeReconstruction/vtkPlusPasteSliceIntoVolumeHelperCommon.h
Missing header include
Incorrect macro token used, concatenation not wanted
=> re #1163 fixing compile issues on Linux

src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
Trying to fix the build errors caused by the (premature) update of OpenIGTLinkIO
=> re #1171 Fixed compile errors due to name changes in OpenIGTLinkIO

src/PlusDataCollection/Testing/CMakeLists.txt, src/PlusDataCollection/Testing/vtkWinProbeVideoSourceTest.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Also tests WriteConfiguration
Uses a different config file for the unit test
=> re #1194 Adding TGC (requires WinProbeSDK-1.3)

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx, src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.h
internal class cleanup, removing serial numbers, simplifying the class, reducing duplication, removing persistence and PreTMatrix, adding per DataSource ToolReferenceFrame in order to support compounding transforms by physically combining stages
=> re #1061 Supporting multiple coreXY configurations

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This is a follow-up to #73. I tested it, the new code behaves the same.
=> re #1194 Simplifying code by using existing XML vector methods

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx
=> re #1061 minor code style

src/PlusDataCollection/PlusSerialLine.cxx, src/PlusDataCollection/PlusSerialLine.h, src/PlusDataCollection/vtkPlusGenericSerialDevice.cxx, src/PlusDataCollection/vtkPlusGenericSerialDevice.h
Based on the "Serial Communications by Allen Denver":
https://msdn.microsoft.com/en-us/library/ff802693.aspx
=> Supporting the status of CTS and DSR lines over serial port

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx
Closes #180. @jamesobutler can you test?
=> Do not reset origin in InternalConnect()

src/PlusCommon/PlusCommon.cxx, src/PlusCommon/PlusCommon.h, src/PlusCommon/PlusCommon.txx, src/PlusDataCollection/BkProFocus/vtkPlusBkProFocusOemVideoSource.cxx, src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx, src/PlusServer/Commands/vtkPlusVersionCommand.cxx
Using existing string functions, with minor modifications for template flexibility
Setting explicit template arguments in PlusCommon function when used for clarity
=> Minor cleanup for #75

src/PlusDataCollection/OpenCVVideo/vtkPlusOpenCVCaptureVideoSource.cxx, src/PlusDataCollection/OpenCVVideo/vtkPlusOpenCVCaptureVideoSource.h
I have fixed the frame RGB codification in the function vtkPlusOpenCVCaptureVideoSource::InternalUpdate().
=> re #205: exchanging between BGR codification and RGB codification

src/Utilities/xio/AhrsAlgo.h
Relevant issue https://github.com/PlusToolkit/PlusApp/issues/29.
=> re PlusToolkit/PlusApp#29 Modify inverse square function in AhrsAlgo to work on Linux

src/Documentation/UserManual/DeviceOptiTrack.dox, src/PlusDataCollection/OptiTrack/vtkPlusOptiTrack.cxx, src/PlusDataCollection/OptiTrack/vtkPlusOptiTrack.h
Prevents using too much memory with unnecessary calls to GetDataDescriptions()
=> re #170: Added configurable refresh rate for updating OptiTrack track tools

src/PlusDataCollection/StealthLink/vtkPlusStealthLinkTracker.cxx
- ReleaseDataFlag is turned on for all filters when getting the image.
- Catch the bad_alloc exception that is thrown by VTK if an image is still to large, then display an error message and return failure.
The server will still crash if the image is too large in debug mode, however that may be unavoidable, since abort() is called in vtkGenericDataArray in debug mode.
Works on a 512^3 image using 2 bytes for each voxel in both release and debug.
Relevant issue: https://github.com/PlusToolkit/PlusLib/issues/249
=> re #249: Allow StealthLink to send larger images

src/Documentation/UserManual/DeviceOptiTrack.dox, src/PlusDataCollection/OptiTrack/vtkPlusOptiTrack.cxx
=> re #242: Renamed RunMotiveInBackground to ShowMotiveGUI

src/PlusImageProcessing/vtkPlusRfToBrightnessConvert.cxx, src/PlusImageProcessing/vtkPlusRfToBrightnessConvert.h
=> Supporting VTK_INT for RfProcessing and cleaning up the class

src/Documentation/UserManual/DeviceOpenCVVideo.dox, src/PlusDataCollection/OpenCVVideo/vtkPlusOpenCVCaptureVideoSource.cxx, src/PlusDataCollection/OpenCVVideo/vtkPlusOpenCVCaptureVideoSource.h
Adding device index parameter and behaviour to OpenCV video device
=> Fixes #312 Adding device index parameter 

src/PlusDataCollection/BkProFocus/vtkPlusBkProFocusOemVideoSource.cxx, src/PlusDataCollection/BkProFocus/vtkPlusBkProFocusOemVideoSource.h, src/PlusDataCollection/vtkPlusUsDevice.h
The OpenIGTLinkIO pull request have to be handled first: https://github.com/IGSIO/OpenIGTLinkIO/pull/56
=> Moving the ultrasound meta information tag names from PLUS to igtlio.

src/PlusDataCollection/vtkPlusUsImagingParameters.cxx, src/PlusDataCollection/vtkPlusUsImagingParameters.h, src/PlusServer/CMakeLists.txt, src/PlusServer/Commands/vtkPlusGetUsParameterCommand.cxx, src/PlusServer/Commands/vtkPlusGetUsParameterCommand.h, src/PlusServer/vtkPlusCommandProcessor.cxx, src/PlusServer/vtkPlusCommandResponse.h, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
Sent GetUsParameter:
```
<Command Name="GetUsParameter" DeviceId="VideoDevice">
<Parameter Name="DepthMm"/>
<Parameter Name="FrequencyMhz"/>
<Parameter Name="GainPercent"/>
<Parameter Name="TEST"/>
</Command>
```
GetUsParameter response:
```
<CommandReply>
<Parameter Name="DepthMm" Success="true" Value="35"/>
<Parameter Name="FrequencyMhz" Success="true" Value="3.75"/>
<Parameter Name="GainPercent" Success="true" Value="50"/>
<Parameter Name="TEST" Success="false"/>
</CommandReply>
```
Response metadata:
````
DepthMm=35
Error=Invalid parameter TEST. 
FrequencyMhz=3.75
GainPercent=50
Status=FAIL
````
Sent SetUsParameter:
```
<Command Name="SetUsParameter" DeviceId="VideoDevice">
<Parameter Name="DepthMm" Value="35"/>
<Parameter Name="GainPercent" Value="50"/>
<Parameter Name="ABCDEFG" …
```
=> Add GetUsParameter command and change format of SetUsParameter response

src/Documentation/UserManual/UsImagingParameters.dox, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.cxx, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.h
Able to change:
- Depth
- Frequency
- Gain
- Dynamic range
=> Implemented ability to control telemed US parameters remotely

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx
This is useful when multiple transforms need to be recorded which differ only by a constant offset.
=> Reviving PreTMatrix attribute

src/PlusServer/vtkPlusOpenIGTLinkServer.cxx, src/PlusServer/vtkPlusOpenIGTLinkServer.h
Adding small delay and check of proper server startup (server port not available error not caught)
=> Reducing usage of std::pair for more explicitly named struct members

BuildAndTest.bat.in, BuildAndTest.sh.in
@lassoan would you check that the changes to individual test running can be easily updated in any scripts you run?
=> Adding argument parsing to script to enable --track argument to CTest

src/PlusCommon/PlusCommon.cxx, src/PlusCommon/PlusCommon.h, src/PlusServer/Tools/PlusServerRemoteControl.cxx, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
=> Implement a response to the GET_POINT IGTL message type

src/Documentation/UserManual/DeviceAtracsys.dox
Added PLUS compatible SDK version numbers to Atracsys documentation
=> Updated Atracsys documentation

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
The TGC near the face of Winprobe transducer can be now be changed on the fly.
=> ENH: Expose WinProbe TGC First Gain Value

src/PlusCalibration/Testing/PatternLocTest.cxx, src/PlusCommon/Tools/EditSequenceFile.cxx, src/PlusDataCollection/ImageProcessor/vtkPlusImageProcessorVideoSource.cxx, src/PlusDataCollection/LeapMotion/vtkPlusLeapMotion.cxx, src/PlusDataCollection/OpenIGTLink/vtkPlusOpenIGTLinkVideoSource.cxx, src/PlusDataCollection/PlusStreamBufferItem.cxx, src/PlusDataCollection/PlusStreamBufferItem.h, src/PlusDataCollection/SavedDataSource/vtkPlusSavedDataSource.cxx, src/PlusDataCollection/SonixVideo/vtkPlusSonixPortaVideoSource.cxx, src/PlusDataCollection/SonixVideo/vtkPlusSonixVideoSource.cxx, src/PlusDataCollection/Testing/vtkVirtualTextRecognizerTest.cxx, src/PlusDataCollection/VirtualDevices/vtkPlusVirtualTextRecognizer.cxx, src/PlusDataCollection/vtkPlusBuffer.cxx, src/PlusDataCollection/vtkPlusBuffer.h, src/PlusDataCollection/vtkPlusChannel.cxx, src/PlusDataCollection/vtkPlusDataCollector.cxx, src/PlusDataCollection/vtkPlusDataSource.cxx, src/PlusDataCollection/vtkPlusDataSource.h, src/PlusDataCollection/vtkPlusDevice.cxx, src/PlusDataCollection/vtkPlusDevice.h, src/PlusDataCollection/vtkPlusGenericSerialDevice.cxx, src/PlusDataCollection/vtkPlusUsDevice.cxx, src/PlusDataCollection/vtkPlusUsDevice.h, src/PlusOpenIGTLink/igtlPlusUsMessage.cxx, src/PlusOpenIGTLink/vtkPlusIgtlMessageCommon.cxx, src/PlusOpenIGTLink/vtkPlusIgtlMessageCommon.h, src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.cxx
Adding flags to field population where necessary
Reducing redundancy in StreamBufferItem by using igsioFieldMapType instead of duplicated typedef
Requires https://github.com/IGSIO/IGSIO/pull/7
=> Updating PlusLib to use latest IGSIO definitions and igsioFieldMapType

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Updates device to most current API @RMR54
=> ENH:  Update WinProbe Ultravision API function signature

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
IGSIO updates for Capistrano and Winprobe devices
=> Update winprobe capistrano igsio defs

src/PlusDataCollection/OpenHaptics/vtkPlusOpenHapticsDevice.cxx, src/PlusDataCollection/OpenHaptics/vtkPlusOpenHapticsDevice.h
=> Open haptics

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Add function to set/read the frame rate limit for B Mode stream
=> ENH:  Expose BModeFrameLimit in PLUS

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Added function for getting pixel spacing for primary and extra sources. @dzenanz, @sjh26, could you please review this?
=> ENH: Get WinProbe primary and extra source pixel spacing

src/PlusDataCollection/CMakeLists.txt, src/PlusDataCollection/Clarius/vtkPlusClarius.cxx, src/PlusDataCollection/Clarius/vtkPlusClarius.h, src/PlusDataCollection/Testing/CMakeLists.txt, src/PlusDataCollection/vtkPlusDeviceFactory.cxx
According to https://github.com/clariusdev/listener/blob/master/src/include/listen.h , the previous version of vtkPlusClarius needed to add button callback function and Framewidth, FrameHeight as arguments to the clariusInitListener() function.
=> pass new function parameters to clariusInitListener

src/Documentation/UserManual/DeviceTelemed.dox, src/PlusDataCollection/Telemed/TelemedUltrasound.cxx, src/PlusDataCollection/Telemed/TelemedUltrasound.h, src/PlusDataCollection/Telemed/Usgfw2_h.h, src/PlusDataCollection/Telemed/Usgfw2_i.c, src/PlusDataCollection/Telemed/Usgfw2_p.c, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.cxx, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.h, src/PlusDataCollection/vtkPlusUsImagingParameters.cxx, src/PlusDataCollection/vtkPlusUsImagingParameters.h, src/PlusServer/Commands/vtkPlusGetUsParameterCommand.cxx, src/PlusServer/Commands/vtkPlusSetUsParameterCommand.cxx
- Updated the Telemed USGFW SDK version to 4.0. There are accompanying PLTools & PlusBuild PRs including the updated libs / build scripts.
- Added ProbeId config attribute to allow the selection of different transducers on the same probe.
- Implemented command and config attribute to enable setting of the focus depth of the image.
=> Update to Telemed SDK v4.0, adding probe selection & focus depth control

src/Documentation/UserManual/DeviceTelemed.dox, src/PlusDataCollection/Telemed/TelemedUltrasound.cxx, src/PlusDataCollection/Telemed/TelemedUltrasound.h, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.cxx, src/PlusDataCollection/Telemed/vtkPlusTelemedVideoSource.h, src/PlusDataCollection/vtkPlusUsImagingParameters.cxx, src/PlusDataCollection/vtkPlusUsImagingParameters.h
Also renamed parameter to FocusDepthPercent.
=> Added unit (percent) to FocusDepth UsParameter. 

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
=> BUG: set shutter mode properly for acquiring correction frames

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h, src/PlusDataCollection/Testing/vtkAndorVideoSourceTest.cxx
Accompanying data PR: https://github.com/PlusToolkit/PlusLibData/pull/37.
=> Updates and fixes to Andor camera

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
There are several changes here which make interfacing with the Andor devices in downstream code easier, such as added checks to see whether the acquisition thread is running, as well as some small bug fixes.
cc @dzenanz and @jamesobutler for review,
and @jrojasUNC for commits related to the bad pixel processing and the counts/sec -> counts change
=> ENH: Several changes to improve usability of Andor device

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
Small oversight with Andor frame transforms.
cc @jamesobutler for review
=> BUG: Add frame field transform status OK to Andor manual transform

src/Documentation/UserManual/DeviceAzureKinect.dox
- Remove x86 compatibility (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1184)
=> DOC: Update Azure Kinect documentation

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
This updates the WinProbe frame collection to use the timestamp that is now packed in the WPDXGetFusedTexData returned data. This method returns a rendered frame such as one that has combined multiple angle frames as part of spatial compounding. The framecallback data is an un-rendered frame and is signaled on individual angle frames. Therefore this change prevents an un-rendered frame's timestamp being paired to rendered frames image data. This issue was observed as older image data being given a newer timestamp than expected. Now the oldest timestamp of the unrendered frames that went into a rendered frame is provided as the rendered frame timestamp.
I have confirmed with hardware that the image data and corresponding timestamp better align now when using WPDXGetFusedTexData data …
=> BUG: Fix wrong timestamp paired with rendered WinProbe frame

src/PlusDataCollection/AzureKinect/vtkPlusAzureKinect.cxx
* Fix issue
* Add warning for frame rate ambiguity
Fixes #894
=> re #894: Fix bad frame rate handling in Azure Kinect

src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx
Added support for Atracsys stk300 device
Fixed issue where options were not set because of the embedded processing
=> ENH Improved SpryTrack support

src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.h
Added methods to access, from the Atracsys wrapper, the values of device parameters set in the config file
Added a function to access the cameras calibration (intrinsic parameters from the cameras)
=> ENH: Added getters for parameters and cameras calibration

src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx, src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.h
Intelligently detect the available firmware version on the device and utilize new commands if available
Enable support for hardware data averaging performed on NDI device, update timeout accordingly (see API documentation)
=> ENH: Implement support for firmware revision querying and BX2 command support

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h, src/PlusServer/Commands/vtkPlusWinProbeCommand.cxx
Get/Set for the following:
BBubbleContrast, BAmplitudeModulation, BApodizationFNumber, BTransmitLocked
=> ENH: Expose more methods for WinProbe class

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h, src/PlusServer/Commands/vtkPlusWinProbeCommand.cxx
Changes WinProbe class commands for setting filters and exposes methods for microbubble destruction.
@Sunderlandkyl can you take a look?
=> Juanrojas add new winprobe commands
