PlusToolkit/PlusLib

src/PlusOpenIGTLink/igtlPlusClientInfoMessage.cxx, src/PlusOpenIGTLink/igtlPlusTrackedFrameMessage.h, src/PlusOpenIGTLink/igtlPlusUsMessage.cxx
This commit modifies the include statements, so it is compatible with the installed version of openigtlink (as compared to only the built version). This is due to the fact, that OpenIGTLink installs header files to different locations in the install "distribution", specifically, the igtlutil subfolder is just installed into the base include folder.
compatibility witth installed version of OpenIGTLink
=> enable usage of openigtlink install-type files

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
This would cause a crash in usbProbe.dll
=> re #1063 preventing double freeze or double unfreeze

src/CMakeLists.txt, src/PlusCommon/CMakeLists.txt, src/PlusDataCollection/CMakeLists.txt
ExternalProject_Add's CMAKE_CACHE_ARGS should have these:
-DPLUS_USE_SYSTEM_ZLIB:BOOL=ON
-DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}
-DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARY}
-DITK_NO_IO_FACTORY_REGISTER_MANAGER:BOOL=ON
PLUS_USE_SYSTEM_ZLIB should be used in cases when ITK's and VTK's internal zlib build has been disabled.
ITK_NO_IO_FACTORY_REGISTER_MANAGER should be used in all the programs and libraries using itk::ImageFileReader and itk::ImageFileWriter classes. This makes sure there is only a single ITK I/O factory manager.
=> fixes #1181 Support building PlusLib as part of Slicer's superbuild

src/PlusWidgets/CMakeLists.txt
Fix include directory for generated Qt headers under VS2017 Community
and Qt5.7.
=> re #1187 support for VS2017 and Qt5.7

src/PlusDataCollection/MicrosoftMediaFoundation/vtkPlusMmfVideoSource.cxx
I'm using a microsoft Lifecam HD3000 webcam(mmf device) to stream video from a PLUS server into an openIGTLink node.  However, when I set FrameSize="640 480" and VideoFormat="YUY2" in my XML config file the resulting webcam stream has a very poor frame rate (10-15 FPS?).
I ran the [vtkmmfvideosourcetest](https://github.com/PlusToolkit/PlusLib/blob/1e2e3fe3dbd70aa01cfeab6823cd1fab5d9e7c19/src/PlusDataCollection/Testing/vtkMmfVideoSourceTest.cxx) with the --list-video-formats argument to  find the list of supported resolutions. See image below. 
Whenever I set an unsupported FrameSize that is not in the list, the stream will always default to 640x480, but I notice that my frame rate is now much better (30 FPS?). It's unclear why I receive a lower frame rate when I explicitly set it to …
=> Fix MMF device frame rate bug

src/PlusDataCollection/Testing/vtkWinProbeVideoSourceTest.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
extern "C" interface, log frame numbers, wrap around time-stamp counter, changing frame size on the fly, compile fix for VS2013, preventing freezing on 32-bits, disabled time-stamp filtering, turned error into a warning for out of order frames
=> re #1194 improving WinProbe support, requires WinProbeSDK-1.2

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx, src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.h
This handles the case of addresses assigned not starting at 0, which happens when connecting and then disconnecting additional encoders.
=> Use device IDs instead of device addresses

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Due to initialization bug in constructor, I thought these arrays were not initialized - hence fiddling with it in the previous commit.
=> re #1194 Fixing initialization bug and VS2013 compile error

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Some functions got renamed, one of them was being called from Plus wrapper. @jamesobutler can you test whether this is still working correctly with the latest SDK?
=> Supporting WinProbeSDK 2.1

src/Documentation/UserManual/DeviceStealthLink.dox, src/PlusDataCollection/StealthLink/vtkPlusStealthLinkTracker.cxx
By adding the AlwaysTrack="TRUE" attribute to the DataSource, the tool will always be tracked, even if it is not the closest tool to the reference frame. 
`<DataSource Type="Tool" Id="" PortName="" AlwaysTrack="TRUE" />`
If not specified, AlwaysTrack is assumed to be false.
Relevant ticket: https://github.com/PlusToolkit/PlusLib/issues/196
=> re #196: Add support for multiple tracked tools in StealthLink

src/PlusDataCollection/CMakeLists.txt
* The variable _PLUS_USE_OpenCV_VIDEO_ is shown in the list of the no-advanced cached variables
* Checking if the library _openCV_ is active, when the variable _PLUS_USE_OpenCV_VIDEO_ is true
=> re #207: Cmake does not show the variable PLUS_USE_OpenCV_VIDEO

src/Documentation/ApiReference/PlusMainPage.dox, src/Documentation/UserManual/AlgorithmProbeCalibration.dox, src/Documentation/UserManual/ApplicationVolumeReconstructor.dox, src/Documentation/UserManual/CommonCoordinateSystems.dox, src/Documentation/UserManual/DeviceAscension3DG.dox, src/Documentation/UserManual/DeviceBkProFocus.dox, src/Documentation/UserManual/DeviceInterson.dox, src/Documentation/UserManual/DeviceOpenIGTLinkTracker.dox, src/Documentation/UserManual/DeviceOpticalMarkerTracker.dox, src/Documentation/UserManual/DeviceStealthLink.dox, src/Documentation/UserManual/FileSequenceFile.dox, src/PlusCalibration/PatternLocAlgo/PlusFidLabeling.cxx, src/PlusDataCollection/SonixVideo/vtkPlusSonixVideoSource.cxx, src/PlusVolumeReconstruction/vtkPlusFillHolesInVolume.h, src/UsePlusLib.cmake.in
Update documentation and references to Assembla to reference the corresponding GitHub locations.
Relevant issue: https://github.com/PlusToolkit/PlusLib/issues/209
=> re #209: Replace Assembla links with appropriate GitHub links

src/Documentation/UserManual/DeviceNDI.dox, src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx, src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.h
Fixed or Irrelevant Issues:
- Connecting with a baud rate of 19200 always fails with Device->host communication timeout [(Line 973](https://github.com/Sunderlandkyl/PlusLib/blob/e6bc96cd4038613975df002ef27afdb82cd7bd19/src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx#L973)) - probably due to this baud rate is reused for indicating higher speed => document that we do not recommend this baud rate
- Connecting with a baud rate of 14400 results in a "Command is invalid in current mode" error => document that we do not recommend this baud rate
- Frequent errors caused by the Probe() function.
- Fixed in https://github.com/PlusToolkit/ndicapi/pull/7
- Frame number is incorrect: => test if it is a parsing issue
- The frame number returned at [Line …
=> Fix for connection issues with NDI Polaris

src/PlusServer/Testing/CMakeLists.txt
The test hangs on Linux waiting for mutex locks in vtkPlusOpenIGTLinkClient::SendCommand() and vtkPlusOpenIGTLinkClient::SendMessage().
This only happens when the PlusServer process is launched from PlusServerRemoteControl, but not when it's started separately.
For now, the conclusion is that we will disable the test on Linux, and potentially try to fix this at a later time.
Relevant issue: https://github.com/PlusToolkit/PlusLib/issues/246
=> re #246: Disable PlusServerOpenIGTLinkCommandsTest on Linux

src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.cxx, src/PlusServer/vtkPlusCommandProcessor.cxx, src/PlusServer/vtkPlusCommandProcessor.h, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
Restore previous functionality that allowed images to be imported from the StealthStation through OpenIGTLink.
Relevant issue: https://github.com/PlusToolkit/PlusLib/issues/249
=> re #249: Fix crash caused by importing images from StealthStation

src/Documentation/UserManual/DeviceStealthLink.dox, src/PlusDataCollection/StealthLink/vtkPlusStealthLinkTracker.cxx, src/PlusDataCollection/StealthLink/vtkPlusStealthLinkTracker.h
By setting the device attribute: ImageTransferRequiresPatientRegistration to FALSE, images can be downloaded from the StealthStation, even without a registration, in which case the default transform will be used.
=> Allow images to be downloaded from StealthStation when registration is not found

src/PlusCommon/PlusCommon.cxx, src/PlusCommon/PlusCommon.h, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx, src/PlusDataCollection/vtkPlusChannel.cxx, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
A new macro is introduced which eases avoidance of repeating error messages in the log. It is applied in US Digital encoders, Capistrano ultrasound, and a few key places in PlusChannel and OpenIGTLinkServer. Closes #256.
=> Do not swamp the log with the exact same message

src/PlusWidgets/CMakeLists.txt
CMake 3.10.0 automoc puts generated files in ..../include_<Config> whereas 3.8-3.9.6 put them in ..../include.
=> re #283: Updating PlusLib for CMake 3.10.0

src/PlusWidgets/CMakeLists.txt
Tested and confirmed successful first time builds for CMake 3.7.2, 3.9.6, 3.10.0 and newly release 3.10.1.
=> re #283: Fixing CMake update to build first time with 3.8 and above

src/PlusCommon/PlusXmlUtils.h, src/PlusDataCollection/Epiphan/vtkPlusEpiphanVideoSource.cxx, src/PlusDataCollection/MicrosoftMediaFoundation/vtkPlusMmfVideoSource.cxx, src/PlusOpenIGTLink/PlusIgtlClientInfo.cxx, src/PlusOpenIGTLink/PlusIgtlClientInfo.h, src/PlusOpenIGTLink/igtlPlusClientInfoMessage.cxx, src/PlusOpenIGTLink/igtlPlusClientInfoMessage.h, src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.cxx, src/PlusServer/Commands/vtkPlusRequestIdsCommand.cxx, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx, src/PlusVolumeReconstruction/vtkPlusVolumeReconstructor.cxx
This prevents disconnects due to insufficient bandwidth on a network. Hopefully no longer necessary if image compression sending is implemented.
=> Enable a configurable option to toggle send blocking on client sockets.

src/PlusCommon/vtkPlusAccurateTimer.cxx, src/PlusDataCollection/vtkPlusTimestampedCircularBuffer.h
PlusLib failed to compile on Ubuntu due to use of deprecated VTK macros / header files
=> Fix VTK deprecated code

src/PlusDataCollection/CMakeLists.txt
This is the PlusLib part of a fix to allow 32-bit versions of Plus (with OptiTrack enabled) to run successfully without having to install the MSVC redistributable.
https://github.com/PerkLab/PLTools/pull/3
https://github.com/PlusToolkit/PlusLib/pull/320
https://github.com/PlusToolkit/PlusBuild/pull/28
=> Add MSVC80 OpenMP dll to OptiTrack 32-bit builds

src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
It was already handled this way for old (V1/V2) OpenIGTLink commands.
This changes the current current V3 commands to use the a similar message format.
Also adds command name and status attributes to response.
=> Store server command response messages in attributes, instead of between tags

src/PlusOpenIGTLink/PlusIgtlClientInfo.cxx, src/PlusOpenIGTLink/PlusIgtlClientInfo.h, src/PlusOpenIGTLink/vtkPlusIgtlMessageCommon.cxx, src/PlusOpenIGTLink/vtkPlusIgtlMessageCommon.h, src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.cxx, src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.h, src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
When OpenIGTLink is compiled with OpenIGTLink_ENABLE_VIDEOSTREAMING and one of the potential video codecs enabled (Currently just VP9 and H264).
Users can specify the encoding type in the config file to send the image as a compressed VideoMessage.
Transforms are not applied to VideoMessage.
Ex.
```
<PlusOpenIGTLinkServer 
MaxNumberOfIgtlMessagesToSend="1" 
MaxTimeSpentWithProcessingMs="50" 
ListeningPort="18944" 
SendValidTransformsOnly="true" 
OutputChannelId="VideoStream" > 
<DefaultClientInfo> 
<MessageTypes> 
<Message Type="IMAGE" />
</MessageTypes>
<ImageNames>
<Image Name="Image" EmbeddedTransformToFrame="Reference" EncodingType="VP90"/>
</ImageNames>
</DefaultClientInfo>
</PlusOpenIGTLinkServer>
```
See list at re #169 for other TODO.
=> re #169: Add option to enable video streaming for image messages

src/PlusDataCollection/Interson/vtkPlusIntersonVideoSource.cxx, src/PlusDataCollection/Interson/vtkPlusIntersonVideoSource.h, src/PlusDataCollection/SonixVideo/vtkPlusSonixPortaVideoSource.cxx, src/PlusDataCollection/SonixVideo/vtkPlusSonixPortaVideoSource.h, src/PlusDataCollection/SonixVideo/vtkPlusSonixVideoSource.cxx, src/PlusDataCollection/SonixVideo/vtkPlusSonixVideoSource.h, src/PlusDataCollection/UsSimulatorVideo/vtkPlusUsSimulatorVideoSource.cxx, src/PlusDataCollection/UsSimulatorVideo/vtkPlusUsSimulatorVideoSource.h, src/PlusDataCollection/vtkPlusUsDevice.cxx, src/PlusDataCollection/vtkPlusUsDevice.h
Resolving redundant behaviour in some US device classes and the base class
Minor code formatting cleanup
=> Cleaning up misnamed variable in vtkPlusUsDevice

src/Documentation/UserManual/PlusServerCommands.dox, src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx, src/PlusServer/Commands/vtkPlusStartStopRecordingCommand.cxx, src/PlusServer/Tools/PlusServerRemoteControl.cxx
https://github.com/PlusToolkit/PlusLib/commit/41fec394f908a32b4d69940dc9136f66d0f3161c adds OutputFilename support to START_ACQUISITION remote command and closes #403.
In order for OutputFilename to actually be used in the START_ACQUISITION remote command without getting overwritten by the STOP_ACQUISITION remote command I changed where the default OutputFilename originates (https://github.com/PlusToolkit/PlusLib/commit/56009bd7a86397d436ea6efa9ea3cacc3149a5fa).  "PlusServerRecording.nrrd" was being used as a default when OutputFilename wasn't specified in the STOP_ACQUISITION command of PlusServerRemoteControl. 
OutputFilename will now use the default as specified in VirtualCapture:
https://github.com/PlusToolkit/PlusLib/blob/05e31501a11c0d7a9241bfc4a7c4420ee8e91463/src/PlusDataCollection …
=> Updating OutputFilename usage in StartStopRecording commands

src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx, src/PlusServer/Commands/vtkPlusStartStopRecordingCommand.cxx
This closes #402.
In StartStopRecordingCommand, moving `SetEnableFileCompression` before `OpenFile` prevents the loophole of allowing compressed metaimage files(that are then unable to be uncompressed) when using the StartStopRecordingCommand.
I've also updated the log warning message in `OpenFile` to use the general "metaimage" term since the user could be requesting to record as mha _or_ mhd.
=> Prevent compression of metaimage when using recording command

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Time Gain Compensation was being returned instead of Focal Point Depth.
=> BUG: Fix incorrect focal point depth returned in WinProbeVideo

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
To get ultrasound stream that matches stream as seen in WinProbe GUI, loading of Default.xml is included as part of connection initialization. 
On loading Default.xml, the speckle size corresponding to transmit frequency is comparable between PLUS stream and stream as observed in WinProbe application GUI.
=> ENH: Load Default XML on WinProbe internal connection

src/PlusDataCollection/vtkPlusGenericSerialDevice.cxx, src/PlusDataCollection/vtkPlusGenericSerialDevice.h
Due to a change in the signature of SendText() in vtkPlusGenericSerialDevice, the method was no longer overridden.
This commit restores the original function signature by creating a new function with the original signature that calls the modified function.
=> Fix SendText command in vtkPlusGenericSerialDevice

src/PlusDataCollection/BkProFocus/vtkPlusBkProFocusOemVideoSource.cxx, src/PlusDataCollection/BkProFocus/vtkPlusBkProFocusOemVideoSource.h
RE: https://github.com/PlusToolkit/PlusLib/issues/486#issuecomment-456881448
I have addressed the bug where the acquisition rate for the BK5000 was hardcoded, rather than using the rate specified in the config file, and tested successfully on our BK5000.
=> Fix acquisition rate bkprofocusoem

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
This also fixes SetFocalPointDepth() tracebacks observed after freezing/unfreezing probe.
=> BUG: Update WinProbe internal start and stop recording

src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx
Two minor changes:
1. Moved LOG_DEBUG output to prevent flooding log with nullptr device names.
2. Fixed std::future_error (no ticket number). Reason: If some devices are not found (dev == nullptr), then tasks.size() < MAX_SERIAL_PORT_NUMBER and we'll wait for a std::future that has not been initialized.
=> Fix std::future_error: No associated state

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
Set Capistrano probe pulse frequency on `setPulseFrequency()` call
=> BUG: Update Capistrano pulse frequency

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
B-mode frames were being ignored when in BRF mode. B-mode frame header (in BRF mode) is now included within `FrameCallback()` checks.
=> BUG: Include B-mode frames when in BRF mode.

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Specified settings in config file including spatial compounding, TX frequency, voltage, scan depth settings were not set up upon device connection.
@sjh26, I've tested this with the up-to-date API, and the stream starts off correctly with specified config file settings.
=> BUG: Set spatial compounding, TX frequency, voltage, scan depth on initial connection

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Pixel spacing has been updated for Rf stream, to account for orientation updates. Decimation factor is also accounted, to get the correct pixel spacing in y (which is in the case for Rf, ElementSpacing[0])
=> BUG: Update WP RF stream pixel spacing

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
m_Mode was getting to set to B-mode, even if M-mode had been enabled. Update m_Mode now only when mode is found to be enabled in getter functions.
=> BUG: Do not update m_mode when getting M-Mode/Rf mode disabled status

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Laggy livestream issue is resolved. Reconstructed volume no longer has the smear. First frame timestamp delay is now included as an offset. 
@dzenanz, @sjh26, Could you please review this?
=> BUG: Offset WinProbe frame timestamp based on frame 0 timestamp

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Set buffer max to 1, and match API updates that optimized frame processing.
=> ENH: Add new buffer call, with WinProbe API updates for frame processing

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Exposed internal Transducer ID getter, which can be used to determine if transducer is connected to board. Can now enable Harmonic mode within B-mode.
=> ENH: Expose transducer internal ID getter, B harmonic mode setter/getter

src/Documentation/UserManual/DeviceVirtualCapture.dox
At this time, the default parameter values for Virtual Capture in the code do not match what the documentation says. This PR updates the documentation to match what is specified in the code.
https://github.com/PlusToolkit/PlusLib/blob/99a41bb4a34ee5a7b1d0d6307aee4442e19c7976/src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx#L41
https://github.com/PlusToolkit/PlusLib/blob/99a41bb4a34ee5a7b1d0d6307aee4442e19c7976/src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx#L60
=> DOC: Update VirtualCapture parameter default values

src/PlusDataCollection/PointGrey/vtkPlusSpinnakerVideoSource.cxx
Spinnaker video source wasn't setting an orientation for the image and as a result, the image couldn't be flipped using the config file. Now it is setting MN as default orientation and users can get the image to flip by specifying a different orientation in the config file (ex. MF).
=> Spinnaker video set an orientation for image

src/SEIDrv/SEIDrv.cpp
This happens commonly if other devices are attached
via serial (COM) ports in addition to USDigital encoders.
=> Do not throw exception if a COM port is already open

src/PlusDataCollection/SonixVideo/itkUlteriusImageIO.cxx, src/Utilities/Ransac/RANSAC.h
Corresponding to https://github.com/PlusToolkit/PlusBuild/pull/57
Handles errors after updating ITK to 5.1.b01 such as:
C:\P\PR19_x64-2\itk-int\include\ITK-5.1\itkExceptionObject.h(19): fatal error C1189: #error:  "Do not include itkExceptionObject.h directly,  include itkMacro.h instead." [C:\P\PR19_x64-2\PlusLib-bin\src\Utilities\Ransac\planeEstimation.vcxproj]
See https://github.com/InsightSoftwareConsortium/ITK/commit/ad0007e8868e4e51825c2f56a1e59a56bf99b69e
=> COMP: Use itkMacro.h instead of itkExceptionObject.h directly

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
The WinProbe device was not closing completely when disconnect was called. This uses 2 new calls as directed by the API developer. Tested with hardware and PlusServer will correctly close all the way now. 
This requires UltraVisionAPI as of November 22nd 2019.
=> BUG: Fix WinProbe not disconnecting all the way

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Exposed `GetBMultiTxCount` and `SetBMultiTxCount` from UltraVision API as `GetBMultiFocalZoneCount` and `SetBMultiFocalZoneCount`. 
Setting the focal zone count to a number higher than 1 allows changes to the focal depth at an index other than 0 to be seen in the winprobe stream.
https://github.com/PlusToolkit/PlusLib/blob/6be00876645c62838ff637dcbc1a3fb2a030fdae/src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h#L86-L89
=> Expose BMultiTxCount from UltraVision API as BMultiFocalZoneCount

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
Capistrano device uses internal probe voltage value from its database to set voltage when unfreezing the probe. Discovered this after setting a voltage, freezing, unfreezing and then the voltage getting set to about 30V, at least while in MIS mode. Other settings update the internal setting like the change proposed here. 
I confirmed with hardware that voltage upon unfreezing the probe is the voltage that was last set.
@dzenanz I know you make some updates to this class if you would like to review.
=> BUG: Fix Capistrano last set voltage not being used when unfrozen

src/PlusDataCollection/VirtualDevices/vtkPlusVirtualVolumeReconstructor.cxx, src/PlusVolumeReconstruction/Tools/VolumeReconstructor.cxx
The change to the function signature of `vtkIGSIOVolumeReconstructor::AddTrackedFrame` in IGSIO/IGSIO commit [47a3e2](https://github.com/IGSIO/IGSIO/commit/47a3e2f30da3bd1a8602e2c85fad1e14ecf40129) breaks the PLUS build. This PR fixes this.
=> BUG: Fix build errors introduced by IGSIO

src/PlusDataCollection/Testing/vtkWinProbeVideoSourceTest.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This PR exposes some of the WinProbe ARFI API, and is largely work by @dzenanz . I've squashed ARFI related commits from https://github.com/dzenanz/PlusLib/commit/2d8f07e5be364e6ae1032ebbf645b7457d054995 to https://github.com/dzenanz/PlusLib/commit/a4e084ba6e17f74c53edab88ae4d531947ed0849 into the one ENH commit, and pulled out the commits from https://github.com/dzenanz/PlusLib/commit/f866d7ca3140c5d2c8cff940d61b83d0aff5b4ff until ARFI for the REFACTOR.
This is currently WIP as @tomekcz and I are confirming the returned data with a phantom. The implementation as it stands adds the ARFI data as one long 2d frame to the extra source which can be manipulated post acquisition, and can be changed later when the API is updated to allow changes to the number of 6x5 repetitions.
@dzenanz …
=> ENH: Add initial ARFI support for WinProbe

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Expose `SetCommand` UltraVision API. 
Also includes a commit fixing a style inconsistency introduced in 85be109e5af059061d32968bfd284879cc7284f1
=> ENH: expose SendCommand from UltraVision API

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
With recent changes to the UltraVision (WinProbe) API, these changes to Set/Get ARFI Focal point depth are required.
This was tested with hardware to confirm the change.
=> ENH: Update WinProbe ARFI focal point depth method

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This exposes ARFIPushOffset for the WinProbe device so that PLUS can set it to different values other than the default.
This was tested with hardware to confirm the change.
=> ENH: Expose WinProbe ARFIPushOffset

src/Documentation/UserManual/DeviceBlackMagicDeckLink.dox
@adamrankin The user documentation link for configuring the BlackMagic device is dead, this commit should fix this.
=> Fixed dead BlackMagic link on configuration documentation page

src/PlusDataCollection/OpticalMarkerTracking/vtkPlusOpticalMarkerTracker.cxx, src/PlusDataCollection/OpticalMarkerTracking/vtkPlusOpticalMarkerTracker.h
Adding autodetection of horizontal image flip for optical marker tracker detection, as this is a problem that is commonly experienced
=> Adding autodetection of horizontal image flip for optical marker tracker detection

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
This is a follow-up to #687, to simplify the method for setting the Capistrano debug output file path.
@Sunderlandkyl, this PR has also been tested with hardware and can be merged as well. Thanks!
=> ENH: Simplify setting Capistrano debug file path

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This fixes some issues that were recently exposed with changes made in 70e363c72fa4e98ef35889dff6cdb3a9b35801ab. Been testing with hardware to confirm that TxCycleCount, TxCycleWidth, TxTxCycleCount and TxTxCycleWidth can be set and get correctly.
=> Various fixes for WinProbe ARFI calls

src/PlusDataCollection/OptiTrack/vtkPlusOptiTrack.cxx
Needs to be verified to work with hardware
=> re PlusToolkit/PlusLib#696: Enforcing NatNet streaming enabled when using AttachToRunningMotive=FALSE

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Previously there would be no failure if connecting to the WinProbe engine with no transducer connected. Now when starting to connect it will fail if there is no transducer plugged in.
Tested with WinProbe hardware
```
Attempting to load: C:\Program Files\MyPlus\bin\Transducers.xml
|ERROR|001.935000| Transducer not connected!| in C:\SP\SPR15_x64\PlusLib\src\PlusDataCollection\WinProbe\vtkPlusWinProbeVideoSource.cxx(780)
|ERROR|001.937000| VideoDeviceLinearArray: Cannot connect to device, ConnectInternal failed| in C:\SP\SPR15_x64\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1239)
|ERROR|001.937000| Unable to connect device: VideoDeviceLinearArray.| in C:\SP\SPR15_x64\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(369)
```
cc: @dzenanz
=> ENH: Fail WinProbe connection if API identifies no transducer connected

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
The following WinProbe API unhandled exception happens when attempting to set focal zone count to 0.  It was being set to 0 when FocalDepth in the config file was being specified to "0 0 0 0".  
```
Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
at UltraVision.Core.SystemInterface.RecreateTables()
at UltraVision.Core.SystemInterface._Execute()
at UltraVision.Core.SystemInterface.Execute()
at UltraVision.Wrapper.SlimSystem.Execute()
at mainCRTStartup()
```
This bug was introduced in changes made in 19481203cc5b6b47f71e61c06e026f701a37dd94.  There we made changes so that a string of "0 0 7 0" was set to one focal zone count by ignoring the other "0" values. However when all are "0" we can't set focal zone count to 0. It must be at least one.
I've tested …
=> BUG: Fix WinProbe API crash due to setting focal zone count to 0

src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
Was running into an issue where stopping and restarting a client many times for a running OpenIGTLinkServer was causing an error with the vtkMultiThreader where the number of opened threads exceeded the defined maximum (https://github.com/Kitware/VTK/blob/e6bd55217240af44749a02f5368cd10ccb0e087a/Common/Core/vtkMultiThreader.cxx#L466). I'm not sure if this is correct, but it seems like the spawned DataReceiverThreads that are created for new connections are not actually cleaned up when the client is disconnected. 
You can recreate the behavior with a simple PlusServer with an MmfVideo device/webcam connected to Slicer via OpenIGTLinkIF and running a script in the interpreter like
```
import time
client_node = slicer.mrmlScene.GetFirstNodeByClass("vtkMRMLIGTLConnectorNode")
for i in …
```
=> BUG: OpenIGTLinkServer does not close data receiver threads for stopped clients

src/PlusServer/vtkPlusOpenIGTLinkServer.cxx
This commit addresses requested changes (#719) for a prior commit f1fab02 which cleans up used thread IDs in the multithreader for OpenIGTLinkServer. The fixed behavior is maintained.
cc @lassoan
=> BUG: Clarify usage of vtkMultiThreader::TerminateThread in OpenIGTLinkServer

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This exposes the IsScanning property for the WinProbe ultrasound device.
Tested this with hardware to confirm that it returns the expected results.
cc: @adamrankin or @Sunderlandkyl for merging
=> ENH: Expose IsScanning method for WinProbe device

src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx, src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.h
I'd like to add this change so that custom header fields can be set from a virtual capture object at the time the file is being written. I wasn't sure how else to do this without making the associated tracked frame list public, so if there's an easier/better solution please let me know. Thanks!
=> ENH: Allow external access for adding custom headers from VirtualCapture

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
I confirmed with official Capistrano SDK installers that these new pulser values were included starting with everything after the cSDK2013 installer (ie cSDK2016/2018/2019). The results of using the current delay values with the newer cSDK versions was invalid frequency output.
**First a table of the current delay values with cSDK versions after cSDK2013:**
|10 MHz | 16 MHz | 20 MHz | 35 MHz |
|---------|----------|----------|----------|
|![10MHz-current](https://user-images.githubusercontent.com/15837524/98130592-6d1dff00-1e88-11eb-868a-a2ba45e7b32f.png)|![16MHz-current](https://user-images.githubusercontent.com/15837524/98130601-7018ef80-1e88-11eb-9675-5873bb65cd28.png)|![20MHz-current](https://user-images.githubusercontent.com/15837524/98130615-74450d00-1e88-11eb-9a1c-c7d5ad9bca3f.png)| …
=> BUG: Define correct Capistrano pulser frequency params for newer SDKs

src/PlusCommon/Tools/EditSequenceFile.cxx, src/PlusVolumeReconstruction/Tools/VolumeReconstructor.cxx, src/PlusVolumeReconstruction/vtkPlusVolumeReconstructor.cxx, src/PlusVolumeReconstruction/vtkPlusVolumeReconstructor.h
I'd like for certain custom headers to be maintained after using tools like VolumeReconstructor and EditSequenceFile.
This PR adds args for each tool which take in a list of custom header fields that are read from the input volume and restored to the output volume.
The work here is a continuation of work from https://github.com/PlusToolkit/PlusLib/pull/731#issuecomment-716957361 where the usage is the same: so that custom header information doesn't need to be restored separately after acquisition and using VolumeReconstructor or EditSequenceFile.
Open to any suggestions here too.
=> Allow custom header fields to be maintained after volume reconstruction or seq edits

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
Previously, the buffer size used in the Andor camera video source class for acquiring image data was not accounting for changes to binning. This PR addresses that and also adds ElementSpacing as a custom field for output frames.
cc: @dzenanz for review
=> Binning and spacing changes for Andor Video Source

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This PR is a series of commits to improve understanding of the Andor camera startup and close connection. `Initialize` is now only called if there are available cameras.  This provides a better understanding of what goes wrong when `Initialize` fails. If fails to initializes it will return early instead of failing to do the various SDK commands. Additional logging of the Camera model and Serial Number on startup also provides better understanding of what was connected.
Previously if the Camera cooler was set to return ambient, it would wait to warm up to the Safe Temperature before calling `ShutDown`. This is unnecessary for most of their most common cameras and appears to be mostly for their older cameras. I have removed this requirement for now. If someone has an old camera and use this …
=> Andor camera startup and close improvements

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This PR includes some changes to the Andor cooling functionality.
The primary change is the addition of `InitializeCoolerState` and `RequireCoolTemp` to replace the single usage of `UseCooling`. The outgoing attribute would turn the cooler on/off on startup and also enforce whether `WaitForCooldown` was required for acquiring images. Now the current cooler state can be maintained on startup instead of turned on/off while a separate attribute controls the requirement to be at the cooled state to acquire images.
Here in PLUS you can do the following situations:
- InitializeCoolerState="false" RequireCoolTemp="false" which won't change the current state of the cooler on startup (a power loss state typically means the cooler starts in an off state) and images can be acquired without being at …
=> Andor cooling no longer has to be set on startup

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
CCD cameras usually have "bad pixels" these are either dead pixels, pixels with significantly lower intensities than neighbors, or pixels whose intensity does not scale with exposure time. Resolution cells (for example 4x4 pixels if bin=4) with more than 20% bad pixels are replaced by the median of surrounding cells.
Supersedes and closes #750.
=> ENH: Add bad pixel correction

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
I mistakenly made the methods `GetUseCosmicRayCorrection` and `SetUseCosmicRayCorrection` be protected.
=> BUG: remove getter and setter of cosmic correction flag from protected section

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This PR exposes setters/getters for camera intrinsics and distance coefficients for the Andor device, since these parameters must be changed for different binning settings.
Other small changes are converting the units for processed Andor images into counts/seconds and fixing a bug where correction images are loaded as the wrong type.
cc @jrojasUNC @dzenanz for review
=> Expose setters for undistortion parameters in Andor device

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This PR puts the acquisition for the Andor device on a separate thread so that the process can be aborted properly through the `AbortAcquisition` SDK call.
cc @dzenanz @jrojasUNC for review
=> Allow Andor device to process acquisition on separate thread

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This exposes a few more methods from the Andor SDK to get the actual HSSpeed and VSSpeed values.  There has been some getters in this Andor PlusLib class, but they were returning the index values. Andor's SDK uses index values to "Set" the value, but then the corresponding Andor SDK Getter returns the actual value.  These changes should make it clearer about if the index or the actual value is being used.
To Maintainers: It would be great if you can "Rebase and Merge" this PR to include the multiple commits here. This will help me manage corresponding updates in a private repo.
cc: @adamaji, @dzenanz
=> Andor index value updates

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This PR makes the Andor device set some frame fields with acquisition parameters (exposure time, binning) on each frame acquisition. Also exposes an `ImageToReference` transform setter so that a tracker doesn't have to be used for setting the frame field transform.
=> ENH: Allow Andor device to set frame fields with acquisition parameters

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
Addresses an issue with the Andor device multithreading similar to https://github.com/PlusToolkit/PlusLib/pull/718#issue-490595951
cc @jamesobutler for review, who has tested this with hardware
=> BUG: Andor device multithreader does not free up closed thread ids

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx
The last bug which prevented successful use of PlusRemoteControl with Capistrano probe.
=> BUG: do not call initialization logic during parameter update

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
Processed Andor frames were not being appropriately scaled to [0, 2^16) when converting from CV_32FC1 to CV_16UC1.
cc @jrojasUNC @dzenanz for review
=> BUG: Andor processed frames not normalized from 32 to 16 bit correctly

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
This changes the code so that instead of setting a different flat image for the different binnings, a single flat image is set and resized to match the size of the binned image. The resized image is saved in a container so the resizing doesn't have to happen every time an image is acquired.
the intensity at the corners of the corrected image is increased due to the correction image used:
@adamaji @dzenanz
=> Set single flat image but resize for different binnings for Andor acquisitions

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx, src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
Exposes another parameter for the Andor device, shutter transfer time (time taken for the shutter to close or open).
cc @jrojasUNC @dzenanz
=> ENH: Expose Andor shutter transfer time setter

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
Small oversight in checking for success for the Andor device shutter transfer time setters.
cc @dzenanz @jamesobutler
=> BUG: Andor shutter transfer time backwards success check

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
This PR fixes an issue with the Andor device where after a set number of captures (around 20 for one data source), no new frames would be added to the data source. This is because the computed filtered timestamp was found as not "`filteredTimestampProbablyValid`". The major change here is to just send the clock as our timestamp. This device generally acquires single frames a few seconds apart, so this should be fine.
A question for maintainers though, what's the motivation for returning `PLUS_SUCCESS` when the created filtered timestamp is found to be probably invalid, and thus the frame isn't added to the data source?
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/vtkPlusBuffer.cxx#L341-L345
=> BUG: Andor drops frames after filtered timestamp stops being valid

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h
Wait until it is needed, either by ReadConfiguration or Connect.
Without this, PlusVersion tries to connect to the Wobbler resulting in the following output:
```text
|ERROR|001.025000| Capistrano finding probes failed| in C:\SP\SPR19_x64b\PlusLib\src\PlusDataCollection\Capistrano\vtkPlusCapistranoVideoSource.cxx(913)
|ERROR|001.029000| Failed to initialize Capistrano US Probe| in C:\SP\SPR19_x64b\PlusLib\src\PlusDataCollection\Capistrano\vtkPlusCapistranoVideoSource.cxx(876)
Supported devices:
- AndorCamera (ver: Andor SDK version: 2.102.30001.0)
- CapistranoVideo (ver: Capistrano BmodeUSB DLL v316, USBprobe DLL v159)
- ChRobotics (ver: Plus-2.9.0)
- FakeTracker (ver: Plus-2.9.0)
- GenericSerialDevice (ver: Plus-2.9.0)
- ImageProcessor (ver: Plus-2.9.0)
- Microchip (ver: Plus-2.9.0)
- …
```
=> Do not initialize Capistrano in constructor

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h
This should make it possible to work without warnings even if not all parameters are specified in the config file. There will be companion PlusLibData PR.
CC: @jamesobutler.
=> Resolving last issues with remote control of Capistrano device

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Minor bug in the winprobe device which saved incorrect element spacings to rf extra source captures. Also cleaned up what seem to be some copy paste typos in conditionals.
cc @jamesobutler for review
=> BUG: Incorrect spacing frame field from winprobe rf capture

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This updates the WinProbe device class to use the latest WinProbe ARFI API. The main changes center around providing full control of the ARFI push and tracking lines rather than only specifying push offset and the rest being hardcoded in the WinProbe API.
I have tested with hardware and I am able to collect and save new ARFI data using a device engine with a `quadBFCount` of 2 and FPGA version of "2020-10-24 24"
cc: @dzenanz @adamaji
=> ENH: Use latest ARFI API configuration

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Originally discovered by @dzenanz in https://github.com/PlusToolkit/PlusLib/pull/838#discussion_r684377965.
=> BUG: Fix set ARFI config string not always returning a PlusStatus

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This includes some clarifications when using a X4BF WinProbe device when doing ARFI. The X4BF continues to use the older API such as ARFIPushOffset, while the X8BF can use the custom specification of that ARFIPushConfigurationString supports.
Dual support will be maintained until X4BF devices are nearly phased out. X4BF devices have not been in production for awhile , but are still used occasionally.
cc: @dzenanz
=> ENH: Clarify ARFIPushConfigurationString usage

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
It was hardcoded to 8 seconds so that upon exiting the method the frame would be available in the frame list. This time was specific to the previously hardcoded 30 pushes method. Push configuration string can be customized now so a time to add to the frame list is dynamic.
If trying to get the frame from the frame list, the video source should be checked to see if it is empty before attempting to get the frame.
cc: @dzenanz @adamaji
=> ENH: Return immediately after ARFIPush

src/Documentation/UserManual/DeviceAtracsys.dox, src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.h
For Atracsys devices, there is an option called "Symmetrise Coordinates" to change the tracker referential from the left camera to the (more conventional) center of the device. This parameter was not included in the device options which are hardcoded in the `enum OPTIONS` in AtracsysTracker.h, so I could have just added it there.
However, after discussion with the sdk devs, we realized that hardcoding the option ids was not really future-proof since these ids could change someday. So we went ahead and rewrote some of the device option handling. This includes an automatic generation of all available options for the connected device, a translator for option names from Plus' nomenclature to Atracsys' one and some robustness improvement for setting the actual values.
The translator is …
=> ENH: Tweaking Atracsys device options handling

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This PR updates the WinProbe device based on the latest updates to the device ARFI API.
The API has dropped ARFI support for X4BF engines. ARFI requires X8BF. ARFI LineRepeatCount has been replaced with PrePushLineRepeatCount and PostPushLineRepeatCount.
@adamaji Can you provide review here with details of testing of these changes with hardware?
=> ENH: Update WinProbe for latest ARFI API

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
These are additional updates based on latest changes to WinProbe API. Main one is that the timeblock for ARFI data is not half of what is used to be. 
When there was ARFI support for X4 and X8BF, the timeblock size was the same for both where the X4 needed to use the full size and X8 used half the size and filled in the other half with zeros.  Since X4BF ARFI support was recently removed, the data now has a timeblock size that is half of what is was before.
I've tested this with hardware and everything works nicely.
@adamaji or @Sunderlandkyl Can you approve and merge? Thanks!
=> Winprobe ARFI update regarding timeblock size

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
With the latest WinProbe API, it was observed that frequency was not being set appropriately. 
The WinProbe API now uses SetTxFreq/GetTxFreq instead of SetTxTxFrequency/GetTxTxFrequency. Using hardware it was confirmed that frequency is now being set appropriately as observed by the image changing.
@adamrankin Can you help proceed with merging? Thanks!
=> BUG: Fix WinProbe frequency not being set appropriately

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Using the latest UltraVisionAPI, the beamformers assume a static array of possible angles based on the number of angles requested. Spatial compounding angle should not be set directly.
I tested this with hardware and things work as intended. Changing spatial compound angle will change spatial compound angle automatically by the API.
cc: @adamrankin or @Sunderlandkyl Can you help with merging this? Thanks!
=> BUG: Fix WinProbe spatial compounding angle allowed to change

src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx, src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.h
Makes sure to fail if either of the 2 required encoders for the coreXY configuration are not present.
cc: @adamaji who can confirm my testing with hardware
=> ENH: Improve US digital connection for coreXY setups

src/PlusDataCollection/vtkPlusDevice.cxx
[BUG: vtkPlusDevice does not clean up threads when stopping recording](https://github.com/PlusToolkit/PlusLib/commit/70aec801a78099004f4ad0f73375c83fd1b011ec) addresses an issue with stopping and starting recording of a device with the base `StartRecording`/`StopRecording` in `vtkPlusDevice` where doing so enough times will throw this error: https://github.com/Kitware/VTK/blob/5fc9b9d1f71b33d8f13e259f9c1fda4105fe00d5/Common/Core/vtkMultiThreader.cxx#L464-L468
Only setting the thread id to -1 does not clean up the associated resources from `vtkMultiThreader`. (Similar fix to https://github.com/PlusToolkit/PlusLib/pull/718)
This came up because we found that `vtkPlusCapistranoVideoSource::FreezeDevice` is not thread safe to call with the device's `InternalUpdate` call. A similar paradigm is …
=> Clean up thread resources spawned from starting/stopping recording

src/PlusConfigure.h.in
The windows preproc definition on Linux causes some issues with
external libs headers using this preproc conditionnally.
Fix #924
=> Fix preproc definition issue on Linux

src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx
Following the release of atracsys sdk 4.7.x for both sprytrack and fusiontrack devices, the options have been updated.
New control options have been added: Integration Time, Compression Threshold and Enable IR Strobe
=> ENH update options for atracsys trackers

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
Small change for exposing overall time gain compensation adjustment for WinProbe devices.
cc @jamesobutler or @nathanbmnt for review
=> ENH: Expose overall gain adjustment for WinProbe device

src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx
Frame options allow to control the output from Atracsys devices. For optimization purposes, one may want to control the maximum number of events, 2d/3d fiducials and markers that can be provided per frame in the output container.
So far, these options were hardcoded in the ftkSetFrameOptions call. For example, the max number of markers was set to 4 while Atracsys trackers are able to track more.
=> ENH Added ability to set Atracsys frame options from config file

src/PlusDataCollection/vtkPlusGenericSerialDevice.cxx, src/PlusDataCollection/vtkPlusGenericSerialDevice.h, src/PlusServer/CMakeLists.txt, src/PlusServer/Commands/vtkPlusGenericSerialCommand.cxx, src/PlusServer/Commands/vtkPlusGenericSerialCommand.h, src/PlusServer/vtkPlusCommandProcessor.cxx
This PR adds vtkPlusCommand functionality for some GenericSerial device commands. Specifically get/set for the RTS line and get for the CTS line.
cc @jamesobutler who's run these changes with hardware.
btw, we've created a separate `GenericSerialRemoteControl` Slicer module based off of https://github.com/openigtlink/SlicerOpenIGTLink/tree/master/UltrasoundRemoteControl to match these commands. Would something like that be helpful to include in SlicerOpenIGTLink?
=> ENH: Add vtkPlusCommand for GenericSerial devices

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
This change is to stop the winprobe engine from pulsing if the transducer is suddenly disconnected.
cc: @jamesobutler for review
=> ENH: Stop Winprobe from scanning if xducer disconnected from engine

src/PlusDataCollection/Atracsys/AtracsysMarkerCreator.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.h
This is a significant update for the Atracsys wrapper. The Marker and Fiducial classes have been rewritten to store all the data provided by the Atracsys API. This data, in addition to events, are now streamed in a custom field along side each tool source.
The max number of fiducials and markers per frame have also both been bumped to 256 to handle many fiducials at the same time.
=> ENH: Atracsys wrapper now also streams all the marker data and events

src/PlusCalibration/vtkProbeCalibrationAlgo/vtkPlusProbeCalibrationOptimizerAlgo.cxx
`COMP: Fix build error with ITK 5.3` aims to fix the following build error I observed when building PlusLib with ITK 5.3.0.
```
7>C:\SP\PR22\PlusLib\src\PlusCalibration\vtkProbeCalibrationAlgo\vtkPlusProbeCalibrationOptimizerAlgo.cxx(105,1): error C2665: 'itk::Rigid3DTransform<TParametersValueType>::SetMatrix': none of the 2 overloads could convert all the argument types [C:\SP\PR22\PlusLib-bin\src\PlusCalibration\vtkPlusCalibration.vcxproj]
7>          with
7>          [
7>              TParametersValueType=double
7>          ]
7>C:\SP\PR22\itk-int\include\ITK-5.3\itkRigid3DTransform.h(128,3): message : could be 'void itk::Rigid3DTransform<TParametersValueType>::SetMatrix(const itk::Matrix<TParametersValueType,3,3> &)' [C:\SP\PR22\PlusLib-bin\src\PlusCalibration\vtkPlusCalibration.vcxproj …
```
=> COMP: Fix build error with ITK 5.3

src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
Undistort files were moved from imgproc to calib3d for Open CV 4. See https://github.com/opencv/opencv/commit/8f1f4273a2484d3191afce1ce5aed9d6ac5cd428
=> ENH: Add OpenCV 4 support to Andor device

src/PlusServer/CMakeLists.txt, src/PlusServer/Commands/vtkPlusGetFrameRateCommand.cxx, src/PlusServer/Commands/vtkPlusGetFrameRateCommand.h, src/PlusServer/vtkPlusCommandProcessor.cxx
This PR adds a vtkPlusCommand for retrieving the frame rate from a channel's data source.
The command input structure looks like
```
<Command Name="GetFrameRate" ChannelId="MyChannelId" />
```
The output structure looks like
```
<CommandReply FrameRate=123.456 FrameRateStdDev=0.123456 />
```
This is helpful for our group since we work with devices with varying frame rates based on changes to certain imaging parameters, and we'd like to monitor those frame rate changes through Slicer.
cc @jamesobutler who's reviewed these changes with hardware
=> ENH: Add command to read frame rate from channel data source

src/SEIDrv/SEIDrv.cpp
This adds some changes to the SEIDrv to explicitly close the SEI bus at time of close. It also adds retry connection attempts based on a USDigital example to address certain issues of failed connections where the connection started soon after another connection ended.
cc: @adamaji
=> SEI disconnection and retry connections

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h, src/PlusServer/Commands/vtkPlusCapistranoCommand.cxx
This PR extends vtkPlusCommand functionality for Capistrano device commands: 
**GetMISMode, GetMISPulsePeriod, GetBidirectionalMode 
SetSweepAngle, GetSweepAngle 
SetDerivativeCompensation, GetDerivativeCompensation 
SetServoGain, GetServoGain 
SetPositionScale, GetPositionScale** 
Example Usage: 
**Command** 
`<Command Name="CapistranoCommand" UsDeviceId="Wobbler"><Parameter Name="GetDerivativeCompensation"/></Command>`
**Reply** 
`<CommandReply><Parameter Name="GetDerivativeCompensation" Success="true" Value="120"/></CommandReply>`
cc [@jamesobutler](https://github.com/jamesobutler) who has tested with hardware
=> ENH: Expose Additional Getter/Setter Functions for Capistrano Device

src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.h
The geometry that describes the tracked markers can be retrieved as a vector of coords x,y,z (float) for each fiducial that composes the marker.
=> ENH get loaded marker geometries through Atracsys wrapper

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h, src/PlusServer/Commands/vtkPlusWinProbeCommand.cxx
This exposes a couple new parameters (InterSet and InterPush delays) for the WinProbe device.
cc: @hannah-morilak for an approving review based on hardware testing
`BUG: Fix Winprobe ARFI cmds failing in debug builds` is for compatibility with the latest WinProbe API which has the InterSet and InterPush parameters.
=> ENH: Expose ARFI InterSet and InterPush delays

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This PR adds various enhancements related to ARFI mode for the WinProbe device. 1) Documentation clarity on setting the inter set delay to 0, and 2) adding an upper bound to ARFI pushes to prevent potential probe burnout from high voltages.
cc @nhjohnston for an approving review with hardware
=> Enhancements for WinProbe ARFI capture

src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx
- Clarification that the maximum number of events is actually the maximum number of **additional** events on top of the default allocation of 20.
- Removed the event `synthTempv1` which is obsolete
- The number of fiducials is now indicated in the "Marker_Info" framefield
- Option names that are not included in the dictionary can now be parsed and applied. Simply replace the spaces by underscores to set any option compatible with the SDK/device.
For example, setting Matching Tolerance and Epipolar Maximum Distance:
```
<Device
Id="TrackerDevice"
Type="AtracsysTracker"
MaxMissingFiducials="0"
MaxMeanRegistrationErrorMm="1.0"
Matching_Tolerance="0.5"
Epipolar_Maximum_Distance="5.0"
ToolReferenceFrame="Tracker"
>
```
=> ENH changes to Atracsys wrapper

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
This moves some initialization and destruction of resources to the internal connect/disconnect calls instead of the device constructor and destructor. This is based on recommendations per https://plustoolkit.github.io/devicecode
"Initialization and destruction of resources is performed during YourDevice::InternalConnect and YourDevice::InternalDisconnect respectively."
cc: @matt-harmody-pki
=> ENH: Speed up PlusVersion check that includes WinProbe device

src/PlusDataCollection/Atracsys/AtracsysMarkerCreator.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.cxx, src/PlusDataCollection/Atracsys/AtracsysTracker.h, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.cxx, src/PlusDataCollection/Atracsys/vtkPlusAtracsysTracker.h
This PR continues the rework of option management started [here](https://github.com/PlusToolkit/PlusLib/pull/1108).
This time, we focus on robustness. All input options (valid and unvalid) are still stored in vtkPlusDevice::Parameters, but it is now possible to access only the valid device options (those that have been successfully set) via vtkPlusAtracsysTracker::GetDeviceOptions().
Additionnally, one can now get the device calibration date.
=> ENH Atracsys: calibration date and better option management

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h, src/PlusServer/Commands/vtkPlusWinProbeCommand.cxx
Get/Set for the following:
BTxCurrent, TxTxCycleCount, TxTxFNumber
=> ENH: Expose additional methods for WinProbe

src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.cxx, src/PlusDataCollection/Capistrano/vtkPlusCapistranoVideoSource.h
This fixes an issue where the Capistrano device would fail to connect the first time after it was power cycled. This will now keep checking if the imaging engine board is present as it waits for the device to re-enumerate after firmware is uploaded to the board during initial connection after being power cycle.
=> BUG: Fix Capistrano device failing to connect after power cycle with cSDK2023 drivers

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx, src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.h
This includes a fix for better handling of the timestamp for rendered WinProbe frames because currently the timestamp offset sometimes gets randomly pushed to the future resulting in new frames getting ignored as they are considered "old" resulting in the stream appearing frozen. With these changes I have no longer observed a spurious frame increasing the timestamp so that when the ultrasound sequencer restarts, new frames always come through rather than the occasional longer than expected freeze of the live stream as we wait for new frames to have a timestamp beyond the spurious far one.
cc: @nhjohnston as another person who has used hardware to confirm these changes.
=> BUG: Fix handling of timestamp for WinProbe rendered frames

src/PlusDataCollection/WinProbe/vtkPlusWinProbeVideoSource.cxx
Changing imaging depth was triggering start recording which was resetting the frame number and resulting in the live stream not streaming.
In general, changing of the scan depth does not require stopping and starting the recording to execute this parameter change.
cc: @nhjohnston for additional review with hardware
=> BUG: Fix WinProbe live stream not recovering upon depth change

.github/workflows/build-itk.yml, .github/workflows/build-plus.yml, .github/workflows/build-vtk.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml
This commit adds GitHub actions that builds + packages Plus.
On commit/PR, the CI action runs x64, x86, x64-static builds. Every day, the nightly script will run and generate packages for nightly release.
=> ENH: Add GitHub actions for CI and Nightly builds
